-- V5 — project_members (T-015). Widens project authorization from T-014's
-- creator-only model to explicit membership + roles.
--
-- Surrogate UUID PK (app-generated by the service, mirroring projects/users) +
-- UNIQUE(project_id, user_id) so a user has at most one membership per project.
-- role is a text+CHECK enum mapped to the ProjectRole Java enum via
-- @Enumerated(STRING) — no Postgres enum type (keeps migrations forward-only and
-- avoids ALTER TYPE churn).
--
-- All three FKs are ON DELETE NO ACTION: this is a tombstone-only system (projects
-- soft-delete, users are not hard-deleted), so a cascade/SET NULL would mask a
-- referential bug rather than express intent.

CREATE TABLE project_members (
    id           uuid        PRIMARY KEY,
    project_id   uuid        NOT NULL REFERENCES projects(id) ON DELETE NO ACTION,
    user_id      uuid        NOT NULL REFERENCES users(id)    ON DELETE NO ACTION,
    role         text        NOT NULL CHECK (role IN ('MEMBER', 'ADMIN')),
    invited_by   uuid        NULL     REFERENCES users(id)    ON DELETE NO ACTION,
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_project_members_project_user UNIQUE (project_id, user_id)
);

CREATE INDEX idx_project_members_user_id ON project_members (user_id);
-- Hot path for the last-admin guard ("all admins of project X") and role lookups.
CREATE INDEX idx_project_members_project_role ON project_members (project_id, role);

-- Backfill: every existing LIVE project's creator becomes its first ADMIN.
-- Soft-deleted projects (deleted_at IS NOT NULL) are skipped. ON CONFLICT makes
-- the block idempotent if re-run. gen_random_uuid() is PG17 core (no extension).
DO $$
DECLARE r record;
BEGIN
    FOR r IN SELECT id AS project_id, created_by AS user_id
             FROM projects
             WHERE deleted_at IS NULL
    LOOP
        INSERT INTO project_members (id, project_id, user_id, role, invited_by, created_at)
        VALUES (gen_random_uuid(), r.project_id, r.user_id, 'ADMIN', NULL, now())
        ON CONFLICT (project_id, user_id) DO NOTHING;
    END LOOP;
END
$$;
