-- V7 — labels + ticket_labels (T-018). The Label aggregate (8th @Entity) and the
-- ticket↔label association (9th @Entity, TicketLabel).
--
-- Both UUID primary keys are generated by the application layer (UUID.randomUUID())
-- — there is INTENTIONALLY no DEFAULT gen_random_uuid() on either id column. Per
-- the AppCDS cold-start hard rule (entity_appcds_hard_rule), entities assign their
-- @Id in code with NO @GeneratedValue, so the EntityManagerFactory never probes the
-- DB for an identity/sequence generator during the Dockerfile stage-3 no-DB boot.
--
-- All FKs are ON DELETE NO ACTION — tombstone-only system; a cascade would mask a
-- referential bug. Label deletion removes its ticket_labels rows explicitly in the
-- service layer (deleteByLabelId before delete), in one transaction.

CREATE TABLE labels (
    id         uuid        PRIMARY KEY,  -- app-generated; no DEFAULT gen_random_uuid() (see header)
    project_id uuid        NOT NULL REFERENCES projects(id) ON DELETE NO ACTION,
    name       text        NOT NULL,
    color      text        NULL,         -- app-layer @Pattern ^#[0-9A-Fa-f]{6}$ when present
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness of a label name WITHIN a project. Functional unique
-- index on (project_id, lower(name)) — standard Postgres DDL, NOT an extension.
-- "Backend" and "backend" collide; the same name in a different project does not.
CREATE UNIQUE INDEX labels_project_id_lower_name_uidx ON labels (project_id, lower(name));
-- Hot path: list all labels of a project (GET /api/projects/{id}/labels).
CREATE INDEX labels_project_id_idx ON labels (project_id);

CREATE TABLE ticket_labels (
    id         uuid        PRIMARY KEY,  -- app-generated; no DEFAULT gen_random_uuid() (see header)
    ticket_id  uuid        NOT NULL REFERENCES tickets(id) ON DELETE NO ACTION,
    label_id   uuid        NOT NULL REFERENCES labels(id)  ON DELETE NO ACTION,
    created_at timestamptz NOT NULL DEFAULT now(),
    -- A ticket carries a given label at most once. Idempotent PUT replace relies on
    -- delete-then-insert, so this also guards against accidental double-insert.
    CONSTRAINT uq_ticket_labels_ticket_label UNIQUE (ticket_id, label_id)
);

-- label_id index: the relational-division AND-filter subquery groups ticket_labels
-- by ticket_id WHERE label_id IN (...). ticket_id index: batch label load
-- (findByTicketIdIn) and per-ticket label fetch on the detail page.
CREATE INDEX ticket_labels_label_id_idx  ON ticket_labels (label_id);
CREATE INDEX ticket_labels_ticket_id_idx ON ticket_labels (ticket_id);
