package io.ngss.atlas.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * Fourth JPA entity (T-014). Maps the V4 {@code projects} table — the first
 * domain aggregate after User/auth.
 *
 * <p>AppCDS cold-start hard rule (see {@code package-info.java} / N6): the
 * {@code id} is application-generated by {@code ProjectService} via
 * {@code UUID.randomUUID()} — NO {@code @GeneratedValue}, no associations, no
 * custom Hibernate types — so the EntityManagerFactory initializes during the
 * Dockerfile stage-3 no-DB AppCDS boot without ever needing a database.
 *
 * <p>Timestamps are PLAIN fields set EXPLICITLY by the service layer (no
 * {@code @PrePersist}/{@code @PreUpdate}, no DB trigger). The narrow mutators
 * ({@link #rename}, {@link #softDelete}) advance {@code updatedAt} themselves
 * from a caller-supplied {@code Instant}.
 */
@Entity
@Table(name = "projects")
public class Project {

  @Id
  @Column(name = "id", nullable = false, updatable = false)
  private UUID id;

  @Column(name = "key", nullable = false, updatable = false)
  private String key;

  @Column(name = "name", nullable = false)
  private String name;

  @Column(name = "description")
  private String description;

  @Column(name = "created_by", nullable = false, updatable = false)
  private UUID createdBy;

  @Column(name = "created_at", nullable = false, updatable = false)
  private Instant createdAt;

  @Column(name = "updated_at", nullable = false)
  private Instant updatedAt;

  @Column(name = "deleted_at")
  private Instant deletedAt;

  /** JPA-only no-args constructor. Do not use directly. */
  protected Project() {}

  public Project(
      UUID id,
      String key,
      String name,
      String description,
      UUID createdBy,
      Instant createdAt,
      Instant updatedAt,
      Instant deletedAt) {
    this.id = id;
    this.key = key;
    this.name = name;
    this.description = description;
    this.createdBy = createdBy;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.deletedAt = deletedAt;
  }

  /**
   * Applies a partial update and advances {@code updatedAt} to {@code now}.
   * {@code createdAt} is never touched. Callers resolve null-means-unchanged
   * semantics before calling.
   */
  public void rename(String newName, String newDescription, Instant now) {
    this.name = newName;
    this.description = newDescription;
    this.updatedAt = now;
  }

  /** Soft-deletes the project: stamps {@code deletedAt} and advances {@code updatedAt}. */
  public void softDelete(Instant now) {
    this.deletedAt = now;
    this.updatedAt = now;
  }

  public UUID getId() {
    return id;
  }

  public String getKey() {
    return key;
  }

  public String getName() {
    return name;
  }

  public String getDescription() {
    return description;
  }

  public UUID getCreatedBy() {
    return createdBy;
  }

  public Instant getCreatedAt() {
    return createdAt;
  }

  public Instant getUpdatedAt() {
    return updatedAt;
  }

  public Instant getDeletedAt() {
    return deletedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof Project other)) {
      return false;
    }
    return id != null && id.equals(other.id);
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(id);
  }
}
