// Runs in the nightly e2e-full workflow (.github/workflows/e2e-full.yml) and locally via npm run e2e:full
//
// Real-backend full-flow E2E (nightly_e2e_deferral): runs ONLY under
// --project=e2e-local (`npm run e2e:local`) against a compose stack at E2E_BASE_URL
// that includes MinIO + the mc-init bucket bootstrap. Excluded from CI. Exercises the
// T-025 attachment flow end to end: init → presigned PUT (direct to MinIO) → finalize
// → list, plus the JPEG thumbnail worker for an image upload.
import { expect, test } from '@playwright/test';

const PASSWORD = 'Attachments123!';

// Valid 1x1 RGBA PNG (proper IHDR/IDAT/IEND + CRCs). MUST be Java-ImageIO-decodable so the
// thumbnail worker can read it: the previous fixture was a 1-bit-grayscale PNG that browsers
// render but ImageIO rejects ("Invalid chunk length") → no thumbnail was ever generated, so the
// thumbnail <img> never appeared. Generated via node:zlib.
const PNG_1X1 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGP4z8DwHwAFAAH/iZk9HQAAAABJRU5ErkJggg==',
  'base64'
);

test('upload a file and an image to a ticket → list + thumbnail appear', async ({ page }) => {
  // Heavier flow (two uploads + the async thumbnail worker + a reload-retry) — give it headroom
  // beyond the 30s project default.
  test.setTimeout(60_000);
  const stamp = Date.now().toString().slice(-5);
  const key = `A${stamp}`;

  await page.goto('/register');
  await page.getByLabel('Email').fill(`atlas-att-${Date.now()}@qa.local`);
  await page.getByLabel('Display name').fill('Attach QA');
  await page.getByLabel('Password').fill(PASSWORD);
  await page.getByRole('button', { name: 'Create account' }).click();
  await expect(page).toHaveURL(/\/projects$/, { timeout: 10_000 });

  await page.getByRole('button', { name: 'New project' }).click();
  await page.getByLabel('Name').fill(`Attach E2E ${stamp}`);
  await page.getByLabel('Key').fill(key);
  await page.getByRole('button', { name: 'Create project' }).click();
  await expect(page).toHaveURL(new RegExp(`/projects/${key}$`), { timeout: 10_000 });

  // Scope "List" to the sidebar nav — ProjectViewToggle (T-027) added a second "List" link.
  await page
    .getByRole('navigation', { name: 'Project sections' })
    .getByRole('link', { name: 'List', exact: true })
    .click();
  await page.getByRole('button', { name: 'New ticket' }).click();
  await page.getByLabel('Title').fill('Has attachments');
  await page.getByRole('button', { name: 'Create' }).click();
  await expect(page.getByText(`${key}-1 created`)).toBeVisible({ timeout: 10_000 });
  await page.getByRole('table').getByText(`${key}-1`).click();
  await expect(page).toHaveURL(new RegExp(`/projects/${key}/tickets/${key}-1$`));

  const section = page.getByTestId
    ? page.getByTestId('attachments-section')
    : page.locator('[data-testid=attachments-section]');
  await expect(section).toBeVisible();

  // Upload a plain text file → appears in the file list.
  await page
    .locator('[data-testid=attachment-input]')
    .setInputFiles({ name: 'notes.txt', mimeType: 'text/plain', buffer: Buffer.from('hello world') });
  await expect(page.getByText('notes.txt')).toBeVisible({ timeout: 15_000 });

  // Upload a real (tiny) PNG → the thumbnail worker runs; an <img> shows up in the grid.
  await page
    .locator('[data-testid=attachment-input]')
    .setInputFiles({ name: 'pixel.png', mimeType: 'image/png', buffer: PNG_1X1 });
  // FIRST wait for the upload to FINALIZE — the image enters the grid as a labelled button.
  // Reloading before finalize would abort the in-flight init→PUT→finalize (it runs async after
  // setInputFiles) and leave the row PENDING with no thumbnail ever generated.
  await expect(page.getByRole('button', { name: 'Open pixel.png' })).toBeVisible({ timeout: 20_000 });
  // The thumbnail is generated by the AFTER_COMMIT worker AFTER finalize, and the attachment list
  // does not poll — the <img> (rendered only once hasThumbnail flips true) needs a refetch following
  // the worker. Reload-and-check until it appears.
  await expect(async () => {
    await page.reload();
    // Exactly one image (pixel.png) is uploaded, so a bare img locator is unambiguous (no .first()).
    await expect(
      page.locator('[data-testid=attachments-section] img')
    ).toBeVisible({ timeout: 3_000 });
  }).toPass({ timeout: 25_000 });
});
